apps/exemplos/urls.py
from django.urls import path, include
from . import views

app_name = 'exemplos'

urlpatterns = [
    path('', views.home, name='home'),
    path('inicio1', views.get_bootstrap, name='inicio'),
    path('containers', views.get_bootstrap_containers, name='containers'),
    path('grids', views.get_bootstrap_grids, name='grids'),
    path('grids2', views.get_bootstrap_grids2, name='grids2'),
    path('grids3', views.get_bootstrap_grids3, name='grids3'),
    path('layouts01', views.get_bootstrap_layouts01, name='layouts01'),
    path('layouts02', views.get_bootstrap_layouts02, name='layouts02'),
    path('layouts03', views.get_bootstrap_layouts03, name='layouts03'),
    path('alin_hor', views.get_bootstrap_alin_hor, name='alin_hor'),
    path('alin_ver', views.get_bootstrap_alin_ver, name='alin_ver'),
    path('utilitarios', views.get_bootstrap_utilitarios, name='utilitarios'),
    path('collapse', views.get_bootstrap_collapse, name='collapse'),
    path('display_flex', views.get_bootstrap_display_flex, name='display_flex'),
    path('display_flexii', views.get_bootstrap_display_flexII, name='display_flexii'),
    path('formulario_i', views.get_bootstrap_formulario_I, name='formulario_i'),
    path('processa_formulario_v1', views.get_bootstrap_processa_formulario_v1, name='processa_formulario_v1'),
    path('formulario_ii', views.get_bootstrap_formulario_II, name='formulario_ii'),
    path('processa_formulario_v2', views.get_bootstrap_processa_formulario_v2, name='processa_formulario_v2'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('exemplos/', include('exemplos.urls')),
    path('login/', include('autenticacao.urls')),
    path('cursos/', include('cursos.urls')),
    path('contato/', include('contato.urls')),
]

apps/exemplos/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.shortcuts import HttpResponseRedirect
from . import form_exemplo
import re

# Create your views here.
def home(request):
    return render(request, 'exemplos/home.html')

def get_bootstrap(request):
    return render(request, 'exemplos/01_helow_word.html')
def get_bootstrap_containers(request):
    return render(request, 'exemplos/02_containers.html')

def get_bootstrap_grids(request):
    return render(request, 'exemplos/04_grids.html')

def get_bootstrap_grids2(request):
    return render(request, 'exemplos/05_grids.html')
def get_bootstrap_grids3(request):
    return render(request, 'exemplos/06_grids.html')
def get_bootstrap_layouts01(request):
    return render(request, 'exemplos/07_layouts.html')

def get_bootstrap_layouts02(request):
    return render(request, 'exemplos/08_layouts.html')

def get_bootstrap_layouts03(request):
    return render(request, 'exemplos/09_layouts.html')

def get_bootstrap_alin_hor(request):
    return render(request, 'exemplos/10_alinhamento.html')

def get_bootstrap_alin_ver(request):
    return render(request, 'exemplos/11_alinhamento.html')

def get_bootstrap_utilitarios(request):
    return render(request, 'exemplos/12_utilitarios.html')
def get_bootstrap_collapse(request):
    return render(request, 'exemplos/13_collapse.html')

def get_bootstrap_display_flex(request):
    return render(request, 'exemplos/14_display_flex.html')

def get_bootstrap_display_flexII(request):
    return render(request, 'exemplos/15_display_flexII.html')
def get_bootstrap_formulario_I(request):
    return render(request,'exemplos/16_forms_parte_i.html')

def get_bootstrap_processa_formulario_v1(request):
    email = request.POST.get('email')
    senha = request.POST.get('senha')

    isEmail, isSenha = validou_form(email, senha)
    if isEmail and isSenha:
        return HttpResponseRedirect("/")
    else:
        context = {
            'email_st': 'is-valid' if isEmail else 'is-invalid',
            'senha_st': 'is-valid' if isSenha else 'is-invalid',
            'email': email,
            'senha': senha,
        }

        return render(request, 'exemplos/16_forms_parte_i.html', context)

def validou_senha(senha):
    regex = '^(?=.*[A-Z])(?=.*[!#@$%&])(?=.*[0-9])(?=.*[a-z]).{6,15}$'
    if (re.search(regex, senha)):
        return True
    else:
        return False

def validou_email(email):
    regex = '^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$'

    if (re.search(regex, email)):
        return True
    else:
        return False
def validou_form(email, senha):
    isEmail = validou_email(email)
    isSenha = validou_senha(senha)
    return isEmail, isSenha

def get_bootstrap_formulario_II(request):
    form = form_exemplo.FormExemplo()

    context ={
        'form': form
    }
    return render(request,'exemplos/17_forms_parte_ii.html', context)

def get_bootstrap_processa_formulario_v2(request):
    form = form_exemplo.FormExemplo()

    if request.method == 'POST':
        form = form_exemplo.FormExemplo(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            senha = form.cleaned_data['senha']
            mensagem = form.cleaned_data['mensagem']
            mensagem_html = f'Formulário validado com sucesso.<br>Email: {email}' \
                            f'<br>Senha: {senha}<br>Mensagem: {mensagem}'
            return HttpResponse(mensagem_html)
        else:
            print("Deu Ruim!!!")


        return render(request, 'exemplos/17_forms_parte_ii.html', {'form': form})

apps/exemplos/templates/exemplos/01_helow_word.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>01 - Ola Mundo</title>
</head>
<body>
  <h1>Ola, Bootstrap 5</h1>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

apps/exemplos/templates/exemplos/02_containers.html
<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>02 - Containers</title>
  </head>

  <body>
    <div class="container-fluid border"><h1>Container Fluid</h1></div>
    <div class="container border"><h1>100% wide until default breakpoint</h1></div>
    <div class="container-sm border"><h1>100% wide until small breakpoint</h1></div>
    <div class="container-md border"><h1>100% wide until medium breakpoint</h1></div>
    <div class="container-lg border"><h1>100% wide until large breakpoint</h1></div>
    <div class="container-xl border"><h1>100% wide until extra large breakpoint</h1></div>

   <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

apps/exemplos/templates/exemplos/05_grids.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>05 - Grids</title>
</head>
<body>
<div class="container">
  <div class="row">
    <div class="border col">1</div>
    <div class="border col">2</div>
    <div class="border col">3</div>
    <div class="border col">4</div>
    <div class="border col">5</div>
    <div class="border col">6</div>
    <div class="border col">7</div>
    <div class="border col">8</div>
    <div class="border col">9</div>
    <div class="border col">10</div>
    <div class="border col">11</div>
    <div class="border col">12</div>
  </div>

    <br>
    <div class="row">
        <div class="border col-6">Coluna-6</div>
        <div class="border col-6">Coluna-6</div>
    </div>
    <br>
    <div class="row">
        <div class="border col-4">Coluna-4</div>
        <div class="border col-8">Coluna-8</div>
    </div>
    <br>
    <div class="row">
        <div class="border col-10">Coluna-10</div>
        <div class="border col-2">Coluna-2</div>
    </div>
    <br>
    <div class="row">
        <div class="border col">Coluna</div>
        <div class="border col-7">Coluna-7</div>
        <div class="border col">Coluna</div>
    </div>
    <br>
    <div class="row">
        <div class="border col">Coluna</div>
        <div class="border col">Coluna</div>
        <div class="border col-7">Coluna-7</div>
        <div class="border col">Coluna</div>
        <div class="border col">Coluna</div>
    </div>
    <br>
    <div class="row">
        <div class="border col-5">Coluna-5</div>
        <div class="border col-7">Coluna-7</div>
        <div class="border col-6">Coluna-6</div>
    </div>
</div>






<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

apps/exemplos/templates/exemplos/06_grids.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>06 - Grids</title>
</head>
<body>
<div class="container">

    <div class="row my-3">
        <div class="border col-6">Coluna-6</div>
        <div class="border col-6">Coluna-6</div>
    </div>
    <br>
    <div class="row">
        <div class="border col-md-4">Coluna-md-4</div>
        <div class="border col-md-8">Coluna-md-8</div>
    </div>
    <br>
    <div class="row">
        <div class="border col-md-4 col-lg-6 col-xl-2">Coluna-md-4 Coluna-lg-6 Coluna-xl-2</div>
        <div class="border col-md-8 col-lg-6 col-xl-10">Coluna-md-8 Coluna-lg-6 Coluna-xl-10</div>
    </div>
    <br>
    <div class="row">
        <div class="border col-sm-4">Coluna-sm-4</div>
        <div class="border col-sm-8">Coluna-sm-8</div>
    </div>



</div>






<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

apps/exemplos/templates/exemplos/07_layouts.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>07 - Layouts</title>
</head>
<body>
  <header>
      <div class="container-fluid bg-primary" style="height: 100px">
          <div class="row">
              <div class="col">ESTE É O CABEÇALHO DA PAGINA</div>
          </div>
      </div>
  </header>
    <div class="main">
        <div class="container-fluid bg-secondary", style="height: 600px">
          <div class="row">
              <div class="col">ESTE É O CORPO DA PÁGINA</div>
          </div>
      </div>

    <footer>
      <div class="container-fluid bg-primary", style="height: 100px">
          <div class="row">
              <div class="col">ESTE É O RODAPÉ DA PAGINA</div>
          </div>
      </div>
    </footer>

    </div>
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

apps/exemplos/templates/exemplos/08_layouts.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>08 - Layouts</title>
</head>
<body>
  <header>
      <div class="container-fluid bg-primary" style="height: 100px">
          <div class="row">
              <div class="col">ESTE É O CABEÇALHO DA PAGINA</div>
          </div>
      </div>
  </header>

    <div class="main">
        <div class="container-fluid bg-secondary">
          <div class="row", style="height: 750px">
              <div class="col-2 bg-warning">
                  <aside>
                      <div class="h3">Menu de Opções</div>
                      <div class="ul">
                          <div class="li">item 1</div>
                          <div class="li">item 2</div>
                          <div class="li">item 3</div>
                          <div class="li">item 4</div>
                          <div class="li">item 5</div>
                          <div class="li">item 6</div>
                      </div>
                  </aside>
              </div>
              <div class="col-8">ESTE É O CORPO DA PÁGINA</div>
              <div class="col-2 bg-warning"> </div>
          </div>
      </div>

    <footer>
      <div class="container-fluid bg-primary", style="height: 100px">
          <div class="row">
              <div class="col">ESTE É O RODAPÉ DA PAGINA</div>
          </div>
      </div>
    </footer>

    </div>
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

apps/exemplos/templates/exemplos/09_layouts.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              crossorigin="anonymous">

        <title>09 - Layouts</title>

    </head>
    <body>

    <div class="container-fluid">

        <header>
            <div class="container-fluid bg-primary text-center" style="height: 100px">
                <div class="row">
                    <div class="col">ESTE É O CABEÇALHO DA PÁGINA</div>
                </div>
            </div>
        </header>

        <div class="main text-center">
             <div class="container-fluid">
                <div class="row justify-content-center" style="height: 750px">

                    <div class="col-8 border bg-secondary">ESTE É O CORPO DA PÁGINA</div>

                </div>
            </div>
        </div>

        <div class="footer">
               <div class="container-fluid bg-primary text-center" style="height: 100px">
                <div class="row">
                    <div class="col">ESTE É O RODAPÉ DA PÁGINA</div>
                </div>
            </div>
        </div>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>

    </body>
</html>

apps/exemplos/templates/exemplos/16_forms_parte_i.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/estilos.css' %}">


    <title>16 - Forms Parte I</title>
</head>
<body>


<div class="container-fluid bg-dark mb-2">
    <div class="row justify-content-center">
        <div class="col-xl-8">
            <header class="bg-dark my-2">

                {% include 'fragments/navbar.html' %}
                {% include 'fragments/carousel.html' %}

            </header>
        </div>
    </div>
</div>

<h1>Login</h1>


<main class="bg-light">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-xl-7">

                <form method="post" action="{% url 'exemplos:processa_formulario_v1' %}">
                    {% csrf_token %}
                    <div class="card p-5">
                        <div class="form-group">
                            <label for="idemail">
                                Endereço de E-mail
                            </label>
                            <input type="email"
                                   name="email"
                                   id="idemail"
                                   placeholder="Digite aqui seu email"
                                   class="form-control {{email_st}}"
                                   required
                                   maxlength="100"
                                   value="{{email}}"
                                   aria-describedby="email_feedback_server"
                            >
                            <div class="invalid-feedback" id="email_feedback_server">
                                Email Inválido
                            </div>
                        </div>

                        <div class="form-group mt-3">
                            <label for="idsenha">
                                Senha
                            </label>
                            <input type="password"
                                   name="senha"
                                   id="idsenha"
                                   placeholder="Digite aqui sua senha"
                                   class="form-control {{senha_st}}"
                                   required
                                   maxlength="20"
                                   value="{{senha}}"
                                   aria-describedby="senha_feedback_server"
                            >
                            <div class="invalid-feedback" id="senha_feedback_server">
                                Senha não atende os critérios básicos de segurança
                            </div>
                        </div>

                        <div class="card-footer ps-0 pt-3">
                            <button type="submit" class="btn btn-primary">Cadastrar</button>
                        </div>

                    </div>
                </form>

            </div>
        </div>
    </div>
</main>

{% include 'fragments/footer.html' %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>

apps/exemplos/templates/exemplos/17_forms_parte_ii.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/estilos.css' %}">


    <title>17 - Forms Parte II</title>
</head>
<body>


<div class="container-fluid bg-dark mb-2">
    <div class="row justify-content-center">
        <div class="col-xl-8">
            <header class="bg-dark my-2">

                {% include 'fragments/navbar.html' %}
                {% include 'fragments/carousel.html' %}

            </header>
        </div>
    </div>
</div>

<h1>Login 2</h1>


<main class="bg-light">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-xl-7">

                <form method="post" action="{% url 'exemplos:processa_formulario_v2' %}">
                    {% csrf_token %}
                    <div class="card p-5">

                        {{ form }}


                        <div class="card-footer ps-0 pt-3">
                            <button type="submit" class="btn btn-primary">Cadastrar</button>
                        </div>

                    </div>
                </form>

            </div>
        </div>
    </div>
</main>

{% include 'fragments/footer.html' %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>