apps/blog/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    path('',views.home, name='home'),
    path('blog',views.blog, name='blog'),
    path('posts/<int:post_id>/',views.post_detail, name='post_detail'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('exemplos/', include('exemplos.urls')),
    path('login/', include('autenticacao.urls')),
    path('cursos/', include('cursos.urls')),
    path('contato/', include('contato.urls')),
]

apps/blog/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Post(models.Model):
    autor = models.CharField(max_length=255)
    titulo = models.CharField(max_length=255)
    resumo = RichTextField(null=True, blank=True)
    subtitulo = models.CharField(max_length=255)
    conteudo = RichTextUploadingField()
    imagem_capa = models.ImageField(null=True, blank=True, upload_to='static/blog/')
    data_publicacao = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.titulo

apps/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
# Create your views here.

def home(request):
    posts = models.Post.objects.order_by('-data_publicacao')[:5]
    context = {
        'posts': posts,
        'primeiro': posts.first(),

    }
    return render(request, 'blog/home.html', context)

def post_detail(request, post_id):
    posts = models.Post.objects.get(pk=post_id)
    context = {
        'posts': posts,
    }
    return render(request, 'blog/post_detail.html', context)

def blog(request):
    posts = models.Post.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/blog.html', context)

apps/blog/templates/blog/blog.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/estilos.css' %}">


    <title>Pagina Inicial</title>
</head>
<body>


<div class="container-fluid bg-dark mb-2">
    <div class="row justify-content-center">
        <div class="col-xl-8">
            <header class="bg-dark my-2">

                {% include 'fragments/navbar.html' %}
                {% include 'fragments/carousel.html' %}

            </header>
        </div>
    </div>
</div>

<h1>blog</h1>


<main class="bg-light">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-xl-7">

                {% for post in posts %}
                    <div class="card mx-5 px-5 py-2">
                    <a class="text-decoration-none text-dark" href="{% url 'blog:post_detail' post.id %}">
                        <img src="{{ post.imagem_capa.url }}"
                             class="card-img-top"
                             alt="imagem do card">
                    </a>
                    <div class="card-body pb-4">
                        <a class="text-decoration-none text-dark" href="{% url 'blog:post_detail' post.id %}">
                            <h4 class="card-title">
                                {{post.titulo}}
                            </h4>
                        </a>
                        <p class="card-text">
                            {{post.conteudo|safe}}
                        </p>
                        <p class="cart-text">
                            <small class="text-muted"> {{post.data_publicacao}}</small>
                        </p>
                        <div class="row">
                            <div class="col-12">
                                <div class="d-flex justify-content-center">
                                    <div class="span me-3 btn">
                                        <i class="fa-solid fa-heart"></i> Curtir
                                    </div>
                                    <div class="span me-3 btn">
                                        <i class="fa-solid fa-comment"></i> Comentar
                                    </div>
                                    <div class="span me-3 btn">
                                        <i class="fa-solid fa-share"></i> Compartilhar
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="my-3"></div>

                {% endfor %}

            </div>
        </div>
    </div>
</main>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>

apps/blog/templates/blog/home.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/estilos.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>Pagina Inicial</title>
</head>
<body>

<div class="container-fluid bg-dark mb-2">
    <div class="row justify-content-center">
        <div class="col-xl-8">
            <header class="bg-dark my-2">

                {% include 'fragments/navbar.html' %}
                {% include 'fragments/carousel.html' %}


            </header>
        </div>
    </div>
</div>

<main class="bg-light">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-xl-8">

                <div class="row">

                    <div class="col-lg-8 d-flex">
                        <div class="card vh-75 vw-100">
                            <a class="text-decoration-none text-dark" href="{% url 'blog:post_detail' posts.0.id %}">
                                <img src="{{ posts.0.imagem_capa.url }}"
                                     class="card-img-top"
                                     alt="imagem do card">
                            </a>
                            <div class="card-body pb-4">
                                <a class="text-decoration-none text-dark" href="{% url 'blog:post_detail' posts.0.id %}">
                                    <h4 class="card-title">
                                        {{posts.0.titulo}}
                                    </h4>
                                </a>
                                <p class="card-text">
                                    {{posts.0.conteudo|safe}}
                                </p>
                                <p class="cart-text">
                                    <small class="text-muted"> {{posts.0.data_publicacao}}</small>
                                </p>
                                <div class="row">
                                    <div class="col-12">
                                        <div class="d-flex justify-content-center">
                                            <div class="span me-3 btn">
                                                <i class="fa-solid fa-heart"></i> Curtir
                                            </div>
                                            <div class="span me-3 btn">
                                                <i class="fa-solid fa-comment"></i> Comentar
                                            </div>
                                            <div class="span me-3 btn">
                                                <i class="fa-solid fa-share"></i> Compartilhar
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 d-none d-lg-flex">

                        <div class="card-body vh-75 vw-100">
                            <img src="{% static 'blog/snipet-01.png' %}"
                                 class="card-img-top"
                                 alt="texto-questão">
                            <div class="card-body">

                                <div class="form-check">
                                    <ul class="list-group list-group-flush">
                                        {% for i in 'ABCDE' %}
                                        <div class="list-group-item">
                                            <input class="form-check-input"
                                                   type="radio"
                                                   name="flexRadioDefault"
                                                   id="flexRadioDefault1">
                                            <label class="form-check-label"
                                                   for="flexRadioDefault1">
                                                ALternatica {{i}}
                                            </label>
                                        </div>

                                        {% endfor %}

                                    </ul>
                                    <a class="text-decoration-none text-dark" href="#" class="btn btn-success mt-2 d-grid">Responder</a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <hr class="my-4">
                <div class="contaniner bg-dark py-3 d-flex justify-content-center rounded">
                    <span>
                        <h1 class="text-info">
                            Posts Recentes
                        </h1>
                    </span>
                </div>
                <hr class="my-4">
                <div class="row row-cols-1 row-cols-md-2 g-4">
                    {% for post in posts|slice:"1:5" %}
                    <div class="col d-flex">
                        <div class="card vh-75 vw-100">
                            <a class="text-decoration-none text-dark" href="{% url 'blog:post_detail' post.id %}">
                                <img src="{{ post.imagem_capa.url }}"
                                     class="card-img-top img-350"
                                     alt="imagem de capa">
                            </a>
                            <div class="card-body pd-3">
                                <a class="text-decoration-none text-dark" href="{% url 'blog:post_detail' post.id %}"><h5 class="card-title">
                                    {{ post.titulo }}
                                </h5></a>
                                <p class="card-text">
                                    {{post.resumo|slice:":250"|safe}} ...
                                </p>
                                <div class="row">
                                    <div class="col-12">
                                        <div class="d-flex justify-content-center">
                                            <div class="span me-3 btn">
                                                <i class="fa-solid fa-heart"></i> Curtir
                                            </div>
                                            <div class="span me-3 btn">
                                                <i class="fa-solid fa-comment"></i> Comentar
                                            </div>
                                            <div class="span me-3 btn">
                                                <i class="fa-solid fa-share"></i> Compartilhar
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>

            </div>
        </div>
    </div>
</main>

{% include 'fragments/footer.html' %}



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>

apps/blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="pt-br">
{% load static %}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/estilos.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>Pagina Inicial</title>
</head>
<body>


<div class="container-fluid bg-dark mb-2">
    <div class="row justify-content-center">
        <div class="col-xl-8">
            <header class="bg-dark my-2">

                {% include 'fragments/navbar.html' %}


            </header>
        </div>
    </div>
</div>

<main class="bg-light">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-xl-8 border-start border-end">
                <hr class="my-5">
                <div class="container-fluid">
                    <div class="flex-row d-flex my-2">

                        <h1>
                            {{posts.titulo}}
                        </h1>

                        <span class="d-flex justify-content-center align-itens-center ms-5">

                            <a href="#" class="text-decoration-none text-dark">
                                <span class="ms-3"
                                      data-bs-toggle="tooltip"
                                      data-bs-placement="top"
                                      title="Compartilhar no Instagram">
                                    <i class="fa-brands fa-instagram-square fa-2xl"></i>
                                </span>
                            </a>

                            <a href="#" class="text-decoration-none text-dark">
                                <span class="ms-3"
                                      data-bs-toggle="tooltip"
                                      data-bs-placement="top"
                                      title="Compartilhar no Facebook">
                                    <i class="fa-brands fa-facebook fa-2xl"></i>
                                </span>
                            </a>

                            <a href="#" class="text-decoration-none text-dark">
                                <span class="ms-3"
                                      data-bs-toggle="tooltip"
                                      data-bs-placement="top"
                                      title="Compartilhar no Twiter">
                                    <i class="fa-brands fa-twitter fa-2xl"></i>
                                </span>
                            </a>

                            <a href="#" class="text-decoration-none text-dark">
                                <span class="ms-3"
                                      data-bs-toggle="tooltip"
                                      data-bs-placement="top"
                                      title="Compartilhar no Link">
                                    <i class="fa-solid fa-link fa-2xl"></i>
                                </span>
                            </a>
                        </span>

                    </div>


                </div>

                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-row align-items-center">
                            <div class="rounded-circle d-flex justify-content-center
                                        align-items-center bg-info avatar">

                                <!-- Inserir imagem aqui... -->

                            </div>
                            <p class="mb-0">
                                <span class="text-muted justify-content-center">
                                    <span class="mx-2 h5">
                                        {{posts.autor}}
                                    </span>
                                    <span>
                                        <i class="fa-solid fa-clock"></i>
                                        <span>
                                            30min
                                        </span>
                                    </span>
                                    <br>
                                    <span class="mx-2">
                                        <i class="fa-solid fa-tags"></i>
                                    </span>
                                    <span>
                                        <a href="#" class="text-decoration-none text-muted">#Basico</a>
                                    </span>
                                    <span>
                                        <a href="#" class="text-decoration-none text-muted">#Python</a>
                                    </span>

                                    <br>

                                    <span class="mx-2">
                                            {{posts.subtitulo}}
                                    </span>

                                </span>
                            </p>
                        </div>
                    </div>
                </div>

                <hr class="my-5">

                <article class="fs-4 px-lg-5 mx-lg-2">
                    {{posts.conteudo|safe}}
                </article>

                <div class="containe-fluid">
                    <div class="row">
                        <div class="col-12">
                            <span>

                                <div class="d-flex justify-content-md-start justify-content-sm-center">
                                    <div class="span me-3 btn">
                                        <i class="fa-solid fa-heart fa-2xl"></i> Curtir
                                    </div>
                                    <div class="span me-3 btn">
                                        <i class="fa-solid fa-comment fa-2xl"></i> Comentar
                                    </div>

                                </div>

                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>


{% include 'fragments/footer.html' %}

</body>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</html>