apps/autenticacao/urls.py
from django.urls import path, include
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login, name='login'),

]

apps/blog/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    path('',views.home, name='home'),
    path('blog',views.blog, name='blog'),
    path('posts/<int:post_id>/',views.post_detail, name='post_detail'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/contato/urls.py
from django.urls import path, include
from . import views

app_name = 'contato'

urlpatterns = [
    path('', views.contato, name='contato'),
    path('mensagens', views.processa_contato, name='mensagens'),

]

apps/cursos/urls.py
from django.urls import path, include
from . import views

app_name = 'cursos'

urlpatterns = [
    path('', views.cursos, name='cursos'),

]

apps/exemplos/urls.py
from django.urls import path, include
from . import views

app_name = 'exemplos'

urlpatterns = [
    path('', views.home, name='home'),
    path('inicio1', views.get_bootstrap, name='inicio'),
    path('containers', views.get_bootstrap_containers, name='containers'),
    path('grids', views.get_bootstrap_grids, name='grids'),
    path('grids2', views.get_bootstrap_grids2, name='grids2'),
    path('grids3', views.get_bootstrap_grids3, name='grids3'),
    path('layouts01', views.get_bootstrap_layouts01, name='layouts01'),
    path('layouts02', views.get_bootstrap_layouts02, name='layouts02'),
    path('layouts03', views.get_bootstrap_layouts03, name='layouts03'),
    path('alin_hor', views.get_bootstrap_alin_hor, name='alin_hor'),
    path('alin_ver', views.get_bootstrap_alin_ver, name='alin_ver'),
    path('utilitarios', views.get_bootstrap_utilitarios, name='utilitarios'),
    path('collapse', views.get_bootstrap_collapse, name='collapse'),
    path('display_flex', views.get_bootstrap_display_flex, name='display_flex'),
    path('display_flexii', views.get_bootstrap_display_flexII, name='display_flexii'),
    path('formulario_i', views.get_bootstrap_formulario_I, name='formulario_i'),
    path('processa_formulario_v1', views.get_bootstrap_processa_formulario_v1, name='processa_formulario_v1'),
    path('formulario_ii', views.get_bootstrap_formulario_II, name='formulario_ii'),
    path('processa_formulario_v2', views.get_bootstrap_processa_formulario_v2, name='processa_formulario_v2'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('exemplos/', include('exemplos.urls')),
    path('login/', include('autenticacao.urls')),
    path('cursos/', include('cursos.urls')),
    path('contato/', include('contato.urls')),
]

apps/blog/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Post(models.Model):
    autor = models.CharField(max_length=255)
    titulo = models.CharField(max_length=255)
    resumo = RichTextField(null=True, blank=True)
    subtitulo = models.CharField(max_length=255)
    conteudo = RichTextUploadingField()
    imagem_capa = models.ImageField(null=True, blank=True, upload_to='static/blog/')
    data_publicacao = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.titulo

apps/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
# Create your views here.

def home(request):
    posts = models.Post.objects.order_by('-data_publicacao')[:5]
    context = {
        'posts': posts,
        'primeiro': posts.first(),

    }
    return render(request, 'blog/home.html', context)

def post_detail(request, post_id):
    posts = models.Post.objects.get(pk=post_id)
    context = {
        'posts': posts,
    }
    return render(request, 'blog/post_detail.html', context)

def blog(request):
    posts = models.Post.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/blog.html', context)

apps/blog/templates/fragments/carousel.html
<div class="container-fluid d-none d-lg-block px-0">
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <svg class="bd-placeholder-img"
                     width="100%"
                     height="100%"
                     xmlns="http://www.w3.org/2000/svg"
                     aria-hidden="true"
                     preserveAspectRatio="xMidYMid slice"
                     focusable="false">
                    <rect width="100%" height="100%" fill="#3A3276"></rect>
                </svg>
                <div class="carousel-caption d-none d-md-block">
                    <h5>Conheça os nosos cursos da Academia Python</h5>
                    <p>Aprenda a construir sites responsivos com Python e Django.</p>
                </div>
            </div>
            <div class="carousel-item">
                <svg class="bd-placeholder-img"
                     width="100%"
                     height="100%"
                     xmlns="http://www.w3.org/2000/svg"
                     aria-hidden="true"
                     preserveAspectRatio="xMidYMid slice"
                     focusable="false">
                    <rect width="100%" height="100%" fill="#198754"></rect>
                </svg>
                <div class="carousel-caption d-none d-md-block">
                    <h5>Siga-nos nas midias sociais</h5>
                    <p>Conheça nosso canal do Youtube e receba dicas, tutoriais gratuitos e
                        fique por dentro das novidades do mundo Geek.</p>
                </div>
            </div>
            <div class="carousel-item">
                <svg class="bd-placeholder-img"
                     width="100%"
                     height="100%"
                     xmlns="http://www.w3.org/2000/svg"
                     aria-hidden="true"
                     preserveAspectRatio="xMidYMid slice"
                     focusable="false">
                    <rect width="100%" height="100%" fill="#ffc107"></rect>
                </svg>
                <div class="carousel-caption d-none d-md-block">
                    <h5>Entre em contato para receber descontos especiais!</h5>
                    <p>Faça parte do nosso grupo do elegram para tirar dúvidas conosco,
                        receber cupons de desconto e muito mais.</p>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"
                data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"
                data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

apps/blog/templates/fragments/footer.html
<footer class="bg-dark py-4 mt-5 {{var_position}}">

    <div class="container-fluid text-white">
        <div class="row justify-content-center">
            <div class="col-lg-2 text-left">
                <h5 class="text-uppercase fw-bold text-info">
                    Quem Somos?
                </h5>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                </p>
            </div>
            <div class="col-lg-4">
                <h5 class="text-uppercase fw-bold text-info">
                    Onde queremos chegar?
                </h5>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aut cumque cupiditate ea, est labore
                    laudantium odit possimus quam quas quasi repellendus suscipit, veritatis. Ex id nemo provident
                    sapiente sint.
                </p>
            </div>
            <div class="col-lg-2">
                <h5 class="text-uppercase fw-bold text-info">
                    Siga-nos nas redes
                </h5>
                <p>
                    <i class="fa-brands fa-youtube"></i>
                    <a href="#" class="text-decoration-none text-white">Youtube</a>
                </p>
                <i class="fa-brands fa-github"></i>
                <a href="#" class="text-decoration-none text-white">Github</a></p>
            </div>
        </div>
    </div>
</footer>

apps/blog/templates/fragments/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid px-0">
        <a class="navbar-brand" href="{% url 'blog:home' %}">Academia Python</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'blog:blog' %}">Blog</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'cursos:cursos' %}">Cursos</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'contato:contato' %}">Contato</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'login:login' %}">Login</a>
                </li>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'exemplos:home' %}">Exemplos</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2"
                       type="search"
                       placeholder="Search"
                       aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>